version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Use pnpm 7.30.1 to install root dependencies
          command: npx pnpm@7.30.1 install
      - run:
          name: Install backend dependencies with pnpm 7.30.1
          command: cd backend && npx pnpm@7.30.1 install
      - run:
          name: Run Tests
          command: cd backend && npx pnpm@7.30.1 test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
