version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd backend && pnpm install
      - run:
          name: Run Tests
          command: cd backend && pnpm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
