version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.19.0
    steps:
      - checkout
      - run:
          name: Use pnpm 7.30.1 to install root dependencies
          command: pnpm install
      - run:
          name: Install backend dependencies with pnpm 7.30.1
          command: cd backend && pnpm install
      - run:
          name: Run Tests
          command: cd backend && pnpm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
